### ISSUE TITLE
Implement Continuous Integration and Deployment (CI/CD) Pipeline

### ISSUE THREAD

**Issue by AbdulRashidReshamwala** [reclaimprotocol/attestor-core#3]
# Implement Continuous Integration and Deployment (CI/CD) Pipeline

## Description

Migrate the existing CI/CD pipeline from GitLab CI to GitHub Actions. This will automate testing, building, and deployment processes, ensuring code quality and streamlining the development workflow.

## Tasks

1. **Set Up GitHub Actions Workflow**
   - Create a `.github/workflows` directory in the repository.
   - Add a new workflow file (e.g., `ci-cd.yml`) to define the CI/CD pipeline.

2. **Migrate Existing GitLab CI Configuration**
   - Review the existing `.gitlab-ci.yml` file.
   - Translate the GitLab CI configuration into GitHub Actions syntax.
   - Ensure all stages (test, deploy) are covered in the new workflow.

3. **Configure Automated Testing**
   - Set up a job to run tests using the existing test scripts.
   - Ensure the job uses the appropriate Node.js version and dependencies.

4. **Configure Automated Deployment**
   - Set up a job to handle deployment to the production environment.
   - Ensure the job includes steps for environment setup, building, and deployment.
   - Use GitHub Secrets to securely store sensitive information (e.g., AWS credentials).

5. **Add Status Badges**
   - Add status badges to the repository's README to display the build and test status.

## Acceptance Criteria

- A new GitHub Actions workflow file is created and committed to the repository.
- The workflow successfully runs automated tests and deployments.
- Status badges are added to the README and display the correct status.
- The GitLab CI configuration is removed from the repository.

## References

- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Existing `.gitlab-ci.yml` file](https://github.com/reclaimprotocol/attestor-core/blob/main/.gitlab-ci.yml)

**Comment by aqeell7** [comment]
on it! assign it to me.

**Comment by AbdulRashidReshamwala** [comment]
@aqeell7 please raise a pr will assign it to you

**Comment by AbdulRashidReshamwala** [comment]
implemented in #8
